### ISSUE TITLE
Should reconsider .dev TLD example in doc

### ISSUE THREAD

**Issue by florentb** [kingkool68/generate-ssl-certs-for-local-development#7]
Now that .dev is an official TLD (owned by Google) you should reconsider your doc example.
The [RFC-6761](https://tools.ietf.org/html/rfc6761) mentions .example, .invalid, .localhost, and .test as alternatives.

**Comment by kingkool68** [comment]
Thanks for the suggestion. The whole reason I go through this rigamarole is because I want to use .dev domains locally which I have done long before Google enforced HSTS (always connect via SSL) for .dev domains.
