### ISSUE TITLE
Fix for Mac 10.15

### ISSUE THREAD

**Issue by WraithKenny** [kingkool68/generate-ssl-certs-for-local-development#9]
There's a set of subtle changes needed for this to continue to work on 10.15. Patch incoming.

**Comment by WraithKenny** [comment]
http://blog.nashcom.de/nashcomblog.nsf/dx/more-strict-server-certificate-handling-in-ios-13-macos-10.15.htm is where I found the fix.

**Comment by makkabi** [comment]
A quick fix that worked for me: I set the number of days in line 47 and 62 of generate-ssl.sh to 824 (instead of 1825).

**Comment by kingkool68** [comment]
This is now merged in.
